### ISSUE TITLE
how can i use this on windows？

### ISSUE THREAD

**Issue by XLionXL** [liangchenwater/ARAP_Parameterization_Deformation#1]

**Comment by liangchenwater** [comment]
Thanks for reaching out. It’s just a course project, without any guarantees on correctness or efficiency. If you want to use this ARAP algorithm, you can use CGAL library, or if you are implementing it yourself, you can surely use my code as reference.

2023年7月23日 下午12:16，XLionXL ***@***.******@***.***>> 写道：

**Comment by XLionXL** [comment]
> 


Thank you for your reply
